name: users
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.8
  get: ^4.6.1
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  random_color: ^1.0.6-nullsafety


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.jpg
    - assets/splash.json
